###
GET http://127.0.0.1:8080/api/exams

###
GET http://127.0.0.1:8080/api/exam/2

###
GET http://127.0.0.1:8080/api/userExam/2

###
GET http://127.0.0.1:8080/api/exams/UNDISTRIBUTED

###
POST http://127.0.0.1:8080/api/exams
Content-Type: application/json

{
  "subject": "职业素质教育",
  "site": "丹青724",
  "needNum": 3,
  "beginTime": "2019-06-05 13:40",
  "endTime": "2019-05-27 15:40",
  "status": "DISTRIBUTED",
  "insertTime": "2019-05-25T23:41:26"
}

###
DELETE http://127.0.0.1:8080/api/exams/5

###
POST http://192.168.43.245:8080/api/manager/modifyExam
Content-Type: application/json

{
  "id": "1",
  "subject": "职业hkjhk",
  "site": "丹青724",
  "needNum": 2,
  "beginTime": "2019-06-05 13:40:55",
  "endTime": "2019-05-27 15:40:45"


}

###
POST http://localhost:8080/api/manager/addUserExam/1
Content-Type: application/json


   [

    {"id": 10},{"id": 8},{"id": 2}

  ]

###
POST http://127.0.0.1:8080/api/manager/addexam
Content-Type: application/json

{
  "subject": "职业素质教育",
  "site": "丹青724",
  "needNum": 3,
  "beginTime": "2019-06-08 21:30:06",
  "endTime": "2019-06-13 21:30:09"

}

###
POST http://127.0.0.1:8080/api/exams/query
Content-Type: application/json

{
  "subject": null,
  "status": null,
  "beginTime": "2019-06-15"
}

###
POST http://localhost:8080/api/manager/addTask
Content-Type: application/json




  {"detail": 10}



###


